company-etags.el

locate-dominating-file returns a directory or nil, so the `(file-regular-p file)` was always `nil`.  Also, the call to `expand-file-name` seemed weird --- the dir should be the optional 2nd argument, not the first.
With the fix, the function should actually return an absolute path to any "TAGS" file, as originally intended.

company-etags-find-table: fix fallback tags file expansion

---

Makefile

This is handy for people working from e.g. a zip or tar snapshot of the git
repo.
I'm currently using this patch in the Debian packaging for company-mode

Makefile: allow package and elpa targets to run without git

---

company.el

I have designed it such that further addition of keywords will not break older versions of company. This is why all keywords are removed before the `pcase`.

[Fix #317] Allow :sorted keyword in grouped back-ends and some doc improvements

---

company-dabbrev-code.el
company-dabbrev.el

This should allow me to write an advice that implements fuzzy matching for `company-dabbrev` and `company-dabbrev-code`. I doubt the extra function-call overhead will cost you very much relative to the real work done by the respective backends.

Allow advising company-dabbrev(-code)? regex generation

---

NEWS.md
company-capf.el

There is currently no way to have custom logic in the `prefix` command for `company-capf`, such as when you want to return a cons-cell instead of a string. This let's you specify a prefix function using `:company-prefix` in the capf-function.

company-capf: Allow custom prefix function

---

company-bbdb.el

Trigger completion for the last incomplete recipient address only,
instead of the whole recipient list.

Fix bbdb completion for multi-recipient messages

---

company.el

I wonder if changing the implementation of `-electric-do` would help with some of the things that are currently tricky to fix (some examples: #310, #439, #454).
IIUC, the main point of electric-do is to introduce a temporary window configuration, and restore it once an unrecognised command is issued. Could this be implemented using a `pre-command-hook`? And would that simplify things?
I've made a rough draft to illustrate that idea, which does fix the `C-h` thing.  I'd love to hear your opinion!

[WIP] Reimplement -electric-do using a pre-command-hook

---

company-tempo.el

I've added a post-completion call to tempo-expand-if-complete so that tempo tags expand. company-tempo-expand seems like it's supposed to take care of that but it has never worked for me.

Option to have tempo expand tags after completion.

---

company-files.el

- Don't rely on `directory-files`; it returns directories without
trailing slash
- Don't use `file-directory-p`; check for trailing / instead
- Don't append children on remotes

[#464] Optimisation and fixes in `company-files`

---

company.el

Fixed issue where if the car of company-backend was a keyword (eg :sorted) the lighter would display that instead of the correct backend. (I believe this necessary due to the "small perf optimization" in company--multi-backend-adapter-candidates

Fixed lighter for grouped backends

---

company.el

Adds autoload cookies to both company-manual-begin and company-complete.
This can be useful if you defer loading of company but also want to bind one of these commands to a keybinding.

Add autoload cookies

---

company.el

As discussed in [this F# mode issue](https://github.com/fsharp/emacs-fsharp-mode/pull/86),
this transformer might be useful for backends returning case insensitive candidates like
[FsAutoComplete](https://github.com/fsharp/FsAutoComplete), because users might prefer the exact prefix match in this case:
```elisp
(let ((sorted-candidates '("AAAa" "aaba" "aaca"))
(company-prefix "aa"))
(company-sort-prefer-same-case-prefix sorted-candidates ))
("aaba" "aaca" "AAAa")
```

New transformer: company-sort-prefer-same-case-prefix

---

company.el

Added company-ac-frontend to mimic auto-complete's delayed popup.
Added company-ac-complete to mimic (approximation) auto-complete's tab behavior.
Added convenience method company-ac-setup to approximate similar
auto-complete behavior without user intervention.
Notes: (Mostly referencing below issue 123)
- Seemed like the feature was never merged in, I pulled in @kencoken's changes and added some more changes (approximating auto-complete's behavior) to bring it to a finish. The naming change recommendations were done as well as pushing the timer cancellation to the precommand.
- From the issue thread, looks like it was might be better to add the additional functionality to the preexisting frontend. I think splitting the frontend out is cleaner and easier to implement (for me anyways).
- …

Add support for auto-complete like behavior

---

company.el

If a backend calls (user-error ...), we want to preserve Emacs' behavior
of not opening a debugger, even when debug-on-error is enabled.

Don't convert user-error signals to error

---

test/files-tests.el

`/lost+found` isn't guaranteed to exist on a filesystem, so this
switches to something that is.

tests: use /bin instead of /lost+found

---

company.el

In *fsharp-mode* with [*company-backend* ](https://github.com/fsharp/emacs-fsharp-mode/blob/master/fsharp-mode-completion.el)completion of this source
```F#
[<EntryPoint>]
let main argv =
printfn "%A" argv.[
```
triggers
```
Debugger entered--Lisp error: (invalid-regexp "Unmatched [ or [^")
string-match("[" ".")
...
company-auto-complete-p("[")
company--continue-failed(stop)
company--continue()
company--perform()
company-post-command()
```

Fix invalid use of string match

---

company-keywords.el

This adds an alias for enh-ruby-mode to ruby-mode for those who use
`enh-ruby-mode` instead of the `ruby-mode` and wants to use the
`company-keywords` backend.

Add alias for enh-ruby-mode for company-keywords

---

company-clang.el

We don't need any job control features. Also Pipes are more efficient and more
robust than PTYs, which Emacs uses by default.
Fixes #620.

Use pipes instead of PTYs to receive output from Clang

---

company.el

The new frontends to preview the common part of candidates was added.
`company-preview-common-frontend`
I changed a little the function `company-preview-show-at-point` to be used 
in this frontend. The default frontend `company-preview-if-just-one-frontend` 
originally uses the function, so both frontends reference it.
Configuration of customized variable `company-frontends` and
the fuction `company-frontends-set` to set the frontends are also
changed since the new frontend is added.
In the default configuration the new frontend is not activated.

Preview the common part of completion candidates

---

company-clang.el

Use tramp-aware `start-file-process' to start completion process

---

company-template.el

In order to be able to forward a field while company-template-field-map is
active, we need to set company-template-nav-map as parent.
This is a regression introduced in #660 
I thought I tested this, but it slipped through.

Set company-template-nav-map as parent of company-template-field-map

---

company-keywords.el

i fount that the company-keywords.el does not contain golang keywords, so i add them

add golang keywords

---

NEWS.md
company-tng.el
company.el

This pull request implements the feature discussed extensively in #526, #517, #343 and #216.
It's implemented as a separate package with minimal configuration required. To enable it just add `company-tng-frontend` to the frontend list. The code is modified from my Gist in #526 in order to enable minimum configuration for the user.
Huge thanks to @dgutov and @aaronjensen for helping me iterate on this feature 😃 
I sent a mail to assign@gnu.org, I'll let you know when the assignment bureaucracy is done.

Company Tab and Go

---

company-tng.el

Following #706, we discovered that the default configuration for `company-tng` behaves funny when there is only one candidate. This PR fixes it by changing the default frontends. More information about the changes is available in the commit messages.
Whether this is the best default configuration is open to discussion, but this PR should be merged anyway to unbreak master.

Fix default company-tng configuration

---

company-clang.el

This patch makes the company-clang backend work much better for me.  I don't know if it will ruin any expected behavior or break anything else.  Please look it over and let me know what you think.
What I can say is that in my limited testing it makes company-clang perform much, much better.  Here is a very small example:
```
struct Foo {};
int main () {
Fo(point)
}
```
In this code file, point is located at position `3:6`.  Using the old code, clang is asked for the code completion at location `3:5`, one character past the beginning of the prefix.  On my machine this results in a [large list of completions](https://pastebin.com/QsvfTNw0) (using clang 5.0.0).  Despite the number of completions, statement is completed to `Foo` anyway.
After the changes in this patch, clang is asked for code …

Place cursor at correct location for completions

---

company-dabbrev.el

Unlike `while-no-input`, this appears to not consume input and it actually helps with the lag.

Abort dabbrev search on input pending

---

.travis.yml

Supports emacs24, emacs25 and emacs-snapshot.
I am not sure about Pros. and Cons. of [container-based build](https://docs.travis-ci.com/user/reference/trusty/#Container-based-with-sudo%3A-false).
If you don't like the change, we can just add emacs25.
https://github.com/iquiw/company-mode/commit/5ff576581bd2d7adbc178a8ba761dafd5c385769

Change to container-based Travis-CI build

---

company-tng.el

This issue was reported by @rswgnu as part of a discussion at #743.
Requiring a match doesn't work with company-tng because the expected behavior is to be able to type any key during completion and it will be inserted into the buffer.
The default value for company-require-match is to require match on explicit action, so we can reproduce as following:
1. Open \*scratch\*
2. Type "(de"
3. M-x company-complete
4. RET RET RET...
The RET won't register because it's not part of the completion but this is not how company-tng should work. The RETs should be inserted into the buffer.

company-tng: default config: Disable company-require-match

---

company-dabbrev.el
company-semantic.el

defcustoms that don't specify `:type` result in byte compiler warnings in Emacs 26+

Fix defcustom

---

company-cmake.el
test/cmake-test.el
test/cmake-tests.el

For example, in the following case as illustrated, we definitely want the company to complete it. Most functions in cmake could be memorized, while these variables are really nasty. We will expect company to help us.
Search `${` backwards from the current point, raise completion if `${` is found and there is no `}` after the matched position.
In the testing conditions, it is used with combination of `company-in-string-or-comment`.

allow company-cmake to complete in strings if prefixed with "${"

---

company.el

Always get candidates with prefix string in `company-diag`

---

company-keywords.el

This changeset enables Thrift IDL support for `company-keywords` backend.

company-keywords: Support thrift-mode

---

NEWS.md
company-capf.el
company.el
test/all.el
test/capf-tests.el

Also, in the company-capf backend, attempt to call :company-match in case
capf definition provides that.
* company-capf.el (company-capf): Look for :company-match prop
in the capf-function return value and use it for `match'.
* company.el (company-backends): Describe new meaning of `match'.o
(company-fill-propertize): Generalize to listp match.
My use case is my other package SLY (https:/github.com/joaotavora/sly) and its ability to "flex-search" completions.  The animated gif should illustrate this:

Allow list of common chunks as response to `match' request

---

company-capf.el
test/capf-tests.el

* company-capf.el (company-capf): Return either a proper list or an
integer.
* test/capf-tests.el (company-basic-capf-highlighting): New test.

Properly fix #809

---

.travis.yml

Supported versions are 24.5, 25.3, 26.1 and master.
master is allowed to be failed.
Resolves #805
Please feel free to close this if you are not in favor of it.

Switch to npostavs/emacs-travis binaries for Travis CI build

---

company-gtags.el

To avoid Emacs bug #5950: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=5950

Define variable alias before referent

---

company.el

As what https://github.com/syl20bnr/spacemacs/issues/11058#issuecomment-411914694 has said, functions called by `company-call-backend` are not at the same `(point)` where `company` begins. But functions in `completion-at-point-functions`  which is used by `company-capf` may rely on the current position to do the completion.
We should restore the point as soon as we have set local variables in `company-pseudo-tooltip-show`.
Solve syl20bnr/spacemacs#11058

Restore point before backends are called

---

company.el

Make sure it returns an actual command.
`lookup-key` returns a number when the key sequence is longer than 1 but it
isn't a valid sequence of prefix characters. The number evaluates to true but
the key isn't in the keymap.
When that happens the completion gets lost. To reproduce, complete a variable
name and type C-x C-s to save.
Fixes #857
Reported-by: Thomas Fini Hansen <https://github.com/xendk>

company: company--company-command-p: Fix lookup-key

---

company-clang.el

Embarcadero ships clang-based compilers with their C++ Builder IDE. Using `company-clang` with their compilers works surprisingly well, provided the changes in this PR are applied.
Example output of `bcc64 --version`:
~~~
Embarcadero C++ 7.40 for Win64 Copyright (c) 2012-2018 Embarcadero Technologies, Inc.
Embarcadero Technologies Inc. bcc64 version 3.3.1 (36707.161adda.9a76976) (based on LLVM 3.3.1)
~~~

Add Embarcadero clang-based compilers to company-clang-version

---

company.el

I had issues where long lines did not wrap in company-doc-buffer. I think this fixes it but this is my first time looking at company-modes code so feel free to criticize this all you want.

Use line-wrap in company doc buffer

---

.travis.yml

You can see Build config validation warnings in https://travis-ci.org/github/company-mode/company-mode/builds/656404873/config.
This PR silence them and correct `allow_failures:` config.

Fix Travis CI Build config

---

company-yasnippet.el

1. It will fix errors caused by snippets that use `file-name-base` function. The `file-name-base` will get the value of `file-name` or `buffer-file-name` . Set the `buffer-file-name` of `doc-buffer` to current file `buffer-file-name`.
2. Considering this situation, we need to catch the error without affecting the user's input, and output the error information to the `*Message*` buffer.
* case 1
```
;;; ${1:$$(file-name-base)}.el --- $2 -*- lexical-binding: t; -*-
;;; Time-stamp: <2020-02-02 17:37:34 stardiviner>
;;; Commentary:
$3
;;; Code:
$0
(provide '$1)
;;; $1.el ends here
```
* works fine
* case 2
Comment the `buffer-file-name` , We will got an error then catch error and output to `*Message*` buffer.  but `company-yasnippet` also work fine. 
error on `*Message*` buffer. It does not …

Improve the behavior

---

NEWS.md
company-tng.el

Disable args insertion in individual backends instead.
Fixes #943.
Fixes #881.

Stop overriding post-completion

---

company-files.el

[company-files] Make post-completion command a dedicated function so that it can be advised easier (e.g: delete file extension on completion).
Signed-off-by: Huy Duong <huy.duong@employmenthero.com>

[company-files] Make post-completion command a dedicated function

---

company.el

Related issue: #380 -- The screenshot on the first comment describes the issue fixed by this patch.
The current implementation specifies the foreground color for tooltips to be black but does not gives the background color on terminals with less color capability, which causes invisible text when the background is black on <88-color terminals.
This patch fixes the problem by giving a default background color. This change does not affect >=88-color terminals.
I believe many people use 256-color terminals or true-color GUI nowadays, but I use an 8-color terminal and want every Emacs package to have a usable default color on it...

Set tooltip background color for terminals with less than 88 colors

---

NEWS.md
company-tng.el
company.el
test/core-tests.el

I've implemented what suggested in https://github.com/company-mode/company-mode/issues/998#issuecomment-671651866.
By adding new var `company-selection-default` that front end like `company-tng` can set on `show` and `hide`, We can make the selection state of `company-mode` temporarily become `nil` when `company-tng` is active.
By that, `company-tng` no longer need to advise `company-fill-propertize` anymore.
Also, by checking `company-selection`, we can have kind of multi binding when press a key and it reacts differently depend on if there's selection or not. E.g; <Enter> key will complete selection or just insert new line when there's no selection.
Let me know if you think this's enough.

company-selection: add company-selection-default to have better support for non-selection popup

---

company.el

Fixes three cases:
1. When FACE is remapped to a single face in face-remapping-alist (which fixes #1022).
2. When FACE remapped to a list of faces (and potentially contains a self-reference, which face-remap allows so faces can refer to their pre-remapped selves).
3. When FACE is a face spec, a missing argument would've caused a wrong-number-of-args error.
Note: I've submitted my FSF CA (thanks for that by the way). Still waiting to hear back.
EDIT: Corrected typo in comment.

Fix company--face-attribute helper

---

company.el

It's me again!
This fixes [another edge case](https://github.com/hlissner/doom-emacs/issues/4092): `company--face-attribute` throws an `invalid face` error when `default` is remapped to a face-spec without an `:inherit` property (e.g. `(:height 1.44)`). To reproduce this: `M-x text-scale-increase`, then invoke company.

Fix company--face-attribute for text-scaled faces

---

company.el

Fix #1030 
The selection is being offset for `company-tng` to work. Before we just offset it in `company-select-next`, that logic should be mved to `company-set-selection`.

company-set-selection: adding offset internally instead of via caller

---

NEWS.md
company.el

I think it's worth having these two functions so users can bind `M-<` (which is usually `beginning-of-buffer`) to `company-select-first` and `M->` (which is usually `end-of-buffer`) to `company-select-last`.

Implement `company-select-first' and `company-select-last'

---

company-gtags.el

* company-gtags.el (company-gtags-executable) : Now default to nil
because the search is made locally if not set.
(company-gtags--executable-p) : Function to search and cache the global
executable locally in the buffer.
(company-gtags--annotation) : Use the new function
company-gtags--executable-p instead of the custom variable
(company-gtags--fetch-tags) : Use the new function
company-gtags--executable-p but execute the process-file from the caller
buffer to have all the context. The output is written back to the
temporal buffer.

Fix company-gtags to work with tramp and multiple locations.

---

NEWS.md
company.el

`company-select-mouse' now delegates to `company-call-frontends` with
`select-mouse'. If at least one frontend reports success (returns t), the
candidate is considered selected. This allows other,
`company-pseudo-tooltip-overlay`-like frontends (e.g. `company-box`) to support
mouse-selection.
To implement this, refactor `company-call-frontends` to return t if at least one
frontend did the same. The mouse event is passed trough the
`company-mouse-event` global, which is `let'-bound in `company-select-mouse'.
Fixes #1044.
Also, I decided to go with a slightly different interface for `company-call-frontends`: I believe it is in general more useful to have a success/failure result from multiple frontends than a list of results, so I decided to return t if at least one frontend did the same. I …

`company-select-mouse': per-frontend interface

---

company.el

We should also check for `company-abort-on-unique-match` in `company--continue`

company--continue: also check for company-abort-on-unique-match

---

company-gtags.el
test/gtags-tests.el

Replacing company-gtags--annotation greedy regexp with the lazy version to make company-gtags behave better with C preprocessor macro-functions.

Refine company-gtags--annotation regexp

---

company.el

This patch does the following.
- Turn variable `company-text-icons-mapping` to custom
- Add `text` and `detect` choice to custom variable `company-format-margin-function`

Add choices, tty, detect

---

README.md

http://company-mode.github.com 404s and suggests http://company-mode.github.io, as the .com version of GitHub pages had been deprecated and stopped redirecting yesterday.

Fix README.md link to homepage

---

company.el

Back in Emacs-21.1, `define-minor-mode` grew keyword arguments to
replace its old positional arguments.  Starting with Emacs-28.1
warning will be omitted if positional arguments are still used.
`:global nil` and `:keymap MODE-map` are not necessary because
those are the defaults.

Avoid positional arguments to define-minor-mode

---

NEWS.md
company.el

Improve default colors for dark themes

---

company.el

Improves visibility of common part(s) of completions with echo-frontends for all built-in light themes.
**before**
**after**
(And transposes the light/dark theme lines to match the order used by the rest of the deffaces.)

Change echo-common face for light themes

---

company.el

Do not break quick-access column when `company-tooltip-limit` > 10.
**before**
**after**
**before**
**after**

Fix quick-access column formatting

---

company.el

Replaces zero-based digits by quick-access bindings digits.
Discussed in #1104.

Fix quick-access numbers shown in echo frontends

---

company.el

Initially suggested in #1103.
This is a minor change, and somewhat arguable. But I still remember being confused by the related piece of the code when reading it in the package for the first time, so would be pleased to see it improved, even if a bit. (Though not opposed with any scenario.)
Just in case,
I also tried (and learned a lot from it) to do something in the spirit of this snippet:
```
(dotimes (i 5)
(let* ((left (format "left is %s" i))
(place 'left))
(set (symbol-value 'place)
(format "i is %s + %s" i (symbol-value place)))
(message "%s" left)))
```
But couldn't make it work in company.el without an error.
The following snippet corresponds to this PR's code change and works equally to the previous one in *scratch*.
```
(dotimes (i 5)
(let* ((left (format "left is %s" i))
(place …
```

Improve readability by minor refactoring

---

company.el

The issue is visible with `(setq company-tooltip-offset-display 'lines)` and non-nil `company-format-margin-function`.
BTW, this `'lines` feature is a very nice one.
**before**
**after**

Fix width of tooltip offset lines number display

---

NEWS.md
company.el

Closes #303.
@dgutov Hi Dmitry, please review the suggested changes.
Built-in **leuven** theme, having customized Company faces, is a representative example:
I've got two more - aside - concerns:
1. The term `numbers` stands for the representation, so `quick-access` (action) or `candidate-id` (entity) could potentially be a better choice. `(defface company-tooltip-quck-access)` or similar perhaps could provide better context to what the face - and functionality overall - does. **But**, the term is used throughout the code, so had to stick with the `numbers`.
The term may also lead to confusion when first met, such as "Which numbers? Numbers of occurrences maybe? Or numbers in the candidates? Or the numbers I type? ... etc".
2. I was confused to find `company--show-numbers` function under …

Add faces for quick-access numbers

---

company.el

```
lib/company/company.el:3221:1: Warning: Lexical argument
shadows the dynamic variable right-margin-width
```

Silence compiler

---

NEWS.md
company.el

[Initially discussed in #1104.](https://github.com/company-mode/company-mode/pull/1104#issuecomment-851591903)
Main points and questions:
- I could eventually test keypad behavior (hurray!) and got these results on Company's master:
- `M-<kp-%d>` completes candidates both with *active-map* and *search-map*.
- `<kp-%d>` does not. Since *search-map* explicitly binds `<kp-%d>` to print numbers, I suppose it'd be quite natural to intent `<kp-%d>` to work the same way with *active-map*.
- Related commit: 43756857.
- #177 evil mode compatibility is still a question. (But `company-complete-number` is still in the code.)
- In the code, I had to put `company--add-quick-access-keys` function definition before its invocation.
With the definition located after invocation, I've spent hours trying to …

Rename and document company-complete-number

---

NEWS.md
company.el
test/frontends-tests.el

WIP for #188 
Hi Dmitry, this is a draft for possible addition of quick-access keys customization. It's planned to be based on PR #1104, which can be influenced by the changes introduced here. I prefer at the moment to keep them separated, hence this draft PRs noise. (Or maybe I'm not aware of a convenient way to have different branches discussed in one PR thread.) If they become tightly coupled, I'll simply close #1104.
Could you help with clarifying the following questions and concerns:
0. Is the direction overall fine with you?  (It doesn't reflect yet *everything* we discussed regarding `company-complete-number` and more work is planned to be put into it overall.)
1. With the current implementation, if to `(setq company-quick-access-keys '("a" "b" "c"))` after `Company` is loaded, key …

Refine quick-access keys customization

---

README.md

Discussed in #1134.
See example of a pinned [Before Asking a Question](https://github.com/yugaego/tmp/discussions). 
Updated `README.md` may serve as a replacement to an earlier suggested `Question / Feature Request` one-entry-point issue template, that provided a link to `Discussions`. 
Note that `Ask a Question` currently links to the 1st post in the Discussions. This would work fine if the first post would have a content such as:
```
1. Read [installation and usage information](http://company-mode.github.io).
2. Read `C-h f company-mode` documentation.
3. Review [Wiki articles](https://github.com/company-mode/company-mode/wiki/Tips-&-tricks).
4. Search in [existing issues](https://github.com/company-mode/company-mode/issues?q=) and …
```

Mention just enabled Discussions

---

company.el

The variable `company-tooltip-offset` was confusing when I was working on one of the previous changes.
An [explanation](https://github.com/company-mode/company-mode/pull/1104#issuecomment-853479362) was provided at that time. This PR adds a docstring to clarify the variable's role.
Additionally, may I suggest the removal of the following variables?
(I understand we declare them here and them assign default values later with `defvar-local` but still, it looks like as a not-needed duplication to my eye, that forced me double think why it is so and where should I put the docstring).
```
(defvar company-pseudo-tooltip-overlay)
(defvar company-tooltip-offset)
```
It's git-logged these `defvar`s were added to fix compilation errors, but I got no compilation errors after removing them (possibly …

Add company-tooltip-offset docstring

---

README.md

In #1137 I also mentioned some other possible minor text updates.
But eventually, the current `Readme` seems to be fine to me (as more concise).
Just in case, I'm attaching here what I also considered for `Readme`:
Read [installation and usage](http://company-mode.github.io/) instructions.
File a bug report in [Issues](https://github.com/company-mode/company-mode/issues).
Ask a question or suggest a feature in [Discussions](https://github.com/company-mode/company-mode/discussions).

Fix link to Discussions QA

---

company.el

Discussed in #1143.
What if to do it this way? I tried to find an approach with the least number of changes. 
`company-pseudo-tooltip-overlay` seem to fit nicely `;; show` subsection of the `;;; pseudo-tooltip`.
`company-tooltip-offset` position is more arguable, though may be justified by the variable definition placed right before its first invocation.
Side question: are there any particular/real reason(s) for not extracting some of the functionality out of `company.el` to separate files? (f.i. starting with echo-frontends).
Based on my own perception, it might be easier to work with smaller files devoted to the specific parts of functionality. (And, potentially, that could make the code look more approachable for fixes/improvements to other programmers).

Merge variables declaration and assignment

---

.github/ISSUE_TEMPLATE/config.yml

The result can be seen at the [tmp repo](https://github.com/yugaego/tmp/issues/new/choose).
`Tips & Tricks` (Wiki) and `Show & Tell` (Discussions) seem to duplicate each other in their roles.
Do you have any preference on how to proceed with them? (I've got none.)
Any ideas and suggestions are very welcome.

Add links to Issues

---

company.el

Closes #1151
As was suggested, the `Control` was added to the `Customize` interface too.
The warnings given in case of an attempted default company keymap overwrite seem to be informative enough and worked smoothly during my checks.
Still, I put this key last in the list, so alternatives would be reviewed first.

Allow Control quick-access modifier key

---

.elpaignore

It seems [ignoring `.github`](https://lists.gnu.org/archive/html/emacs-devel/2021-02/msg01230.html) files may be a good idea, they look as a redundancy on the [package download](https://elpa.gnu.org/devel/company.html).

Elpaignore .github files

---

company-gtags.el
test/core-tests.el

Fix for #1161 .
Uses `fboundp` as suggested in the [Compiler Error docs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Compiler-Errors.html).
@dgutov , I didn't test `company-gtags--executable` in action. Please do so if it's simple for you. Thank you.

Fix compilation warnings on Emacs 25-26

---

.github/workflows/ci.yml
Makefile

Hi Dmitry,
(Hope you're out from zeitnot and are doing fine.)
I've considered several possible setups - referenced below - and chose to keep it (stupid) simple:
`Makefile` already exists, is in use, and can potentially be used in future with fewer number of external dependencies.
Example with the [deliberate fails](https://github.com/yugaego/company-mode/actions/runs/1104317877).
Example with the [real checks](https://github.com/yugaego/company-mode/actions/runs/1104875213).
There's a particular issue: `company-gtags.el:79:47:Error: executable-find called with 2 arguments, but accepts only 1` on [Emacs < 27.1](https://github.com/emacs-mirror/emacs/commit/6f649e77b8512f73b17f03fd795beea9965c4029).
I didn't have a chance to put much attention to it yet: should a fallback be given for …

Add GitHub Actions checks

---

.github/workflows/ci.yml

I was greatly surprised to see the Company Actions running on my fork.
And I [was not alone](https://github.community/t/stop-github-actions-running-on-a-fork/17965/2).
Since the workflows minutes/storage are limited on all accounts, I suggest limit checks triggering to this repo only.

Do not run CI on forks

---

company.el

This missing dot caused `expand-file-name` to receive a list instead of a string, which in turn caused it to fail.

Add missing dot in `company-vscode-icons-mapping`

---

company.el

These minor fixes are intended to make docstrings declared behavior to match the reality: dot-icons are also affected by those user options.
The rest are minor stylistic updates.

Fix docstrings

---

NEWS.md
company.el

This PR suggests using more descriptive faces names, better fitting the rest of the `tooltip` related faces.
Also, the `-fg`/`-bg` part may make it look like `:foreground`/`:background` face attribute is (only) set there.

Rename tooltip scrollbar faces

---

company-files.el
test/files-tests.el

Replaces destructive `cl-delete-if-not` by non-destructive `cl-remove-if-not` to still exclude files when a directory is also configured for exclusion. The added test demonstrates the fixed case. (I checked it on Emacs 28.0.90).
Also improves the docstring and `:type` of this option.

Fix company-files-exclusions docstring and application

---

doc/Makefile
doc/company.texi

Hi Dmitry ,
I didn't figure out why docstring of `company-dabbrev-downcase` says 
> If you set this value to nil, you may also want to set ‘company-dabbrev-ignore-case’ to any value other than ‘keep-prefix’.
Could you elaborate on this?
Your input is welcome on other aspects of the suggested changes too.
This is the last major update I had on my mind at this stage.
The next proper step I think would be to check/polish package archives releases, which I didn't have a chance to look into yet and may need your help with. 
Thanks. And have a nice day!

User manual updates: Extend 'Package Backends' and fix typos

---

company.el

Idle completion isn’t a direct response to a user action, so I believe marking
it as non-essential is justified.

Bind ‘non-essential’ when performing idle completion.

---

NEWS.md
company.el
doc/company.texi
test/core-tests.el

Based on #1264.
I'm still considering if this would be a good idea to apply this change.
It may be convenient considering it in parallel with the suggested manual text. 
So let's keep it open for now, without merging.
My first serious attempt was to use `company-triggered-complete`/`company-triggered-complete-chars` but that proved to be a weak choice on a closer look (as with many other names).
The current choice seems to be self-explanatory (as of today) but its long-ish.

Rename 'auto-commit' user options

---

doc/company.texi

I’ve auto-generated them using the ‘texinfo-all-menus-update’ command in Emacs.

Add section menus to all sections of the manual.

---

company-keywords.el

This list contained keywords that are not PHP reserved words today.
I propose adding the following keywords:
* [Keywords and compile-time constants](https://www.php.net/manual/reserved.keywords.php)
* [Type name for type declaration](https://www.php.net/manual/language.types.declarations.php)
* Frequently mentioned classes/interfaces in code among [Predefined Classes](https://www.php.net/manual/reserved.classes.php)
This PR is same as https://github.com/minad/cape/pull/31.

Add php keywords

---

company-yasnippet.el

Avoid choose value prompts when fetching snippet documentation by setting local buffer variable `yas-prompt-functions` to `'(yas-no-prompt)`. This is needed when a snippet field has multiple values to choose.

company-yasnippet: avoid choose value prompts when fetching snippet doc

---

company.el

Fixes compilation warnings on Emacs snapshot and `(mismatch)` errors shown in `Customize` buffer.

Fix defcustoms syntax

---

.github/workflows/ci.yml

Add `Emacs 28.1` and switch to `ubuntu-latest` (still 20.04 now; 22.04 environment is in beta).

CI: Run tests on latest releases

---

NEWS.md
company.el
doc/company.texi

This is my new attempt at implementing and documenting this feature. Feedback is very much welcome. 
---
`company-show-doc-buffer` now can accept a prefix argument to toggle a new
variable `company-auto-update-doc`.  When this variable is non-nil, it keeps the
documentation buffer up-to-date whenever the selection changes (#1331).

company-show-doc-buffer: Add prefix argument toggle-auto-update

---

company-oddmuse.el
company.el

* company-oddmuse.el (company-oddmuse):
* company.el (company-grab-line): Use `line-beginning-position'
instead of `point-at-bol' which is made obsolete with Emacs 29.

Pacify Emacs 29 compiler warnings

---

company-clang.el
company-dabbrev-code.el
company-dabbrev.el
company.el

* company-clang.el (company-clang):
* company-dabbrev-code.el (company-dabbrev-code):
* company-dabbrev.el (company-dabbrev):
* company.el (company-remove-callback, company-begin-with): Prefix ignored argument with '_'.

Silence warnings about unused lexical argument `ignored'

---

.github/workflows/ci.yml
doc/company.texi

CI filter by repository is not needed since Actions are disabled by default on forks. 
Use the latest libs to prevent [GitHub Actions warnings](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

Bits of Maintenance

---

doc/company.texi

Adds 'company-tooltip-annotation-padding' description.
Fixes Texinfo 7.0 warnings "@pxref should not appear in @w".

doc/company.texi: Add 'company-tooltip-annotation-padding'

---

company.el
test/frontends-tests.el

`posn-col-row` return value relative to the left, which make the overlay appears in completely wrong position when using a RTL language and `bidi-paragraph-direction` set no nil or forcing right-to-left.
To reproduce set bidi-paragraph-direction to right-to-left.

company--posn-col-row: fix wrong col value with RTL direction

---

test/frontends-tests.el

Adds `copy-sequence`, as was suggested in https://github.com/company-mode/company-mode/pull/1387#issuecomment-1615997805

Fix byte-compiler warning

---

.github/workflows/ci.yml

The latest release is added to run tests for it.

CI: run tests on Emacs 29.1

---

NEWS.md
company-dabbrev.el
company-ispell.el
company.el

Implement `keep-prefix` inside the backends that advertise this capability (dabbrev and ispell), using the cache helpers, with the intention to drop support for this backend action at some later date.
Previously described in https://github.com/company-mode/company-mode/issues/285#issuecomment-105237695.
Resolves #285.
Fixes #413, fixes #1072, fixes #1096, resolves #1063, addresses #1226.
The more ambitious full case conversion (upcase/downcase/snake/camel, mentioned in https://github.com/company-mode/company-mode/issues/1096#issuecomment-824949311), is out of scope for this particular change, but could be added later by either altering the new helper, or adding another one. I'm concerned about the performance for certain backends (such as ispell), so maybe the latter.

Add explicit caching mechanism (for backends) and fold the `keep-prefix` logic inside

---

company.el

The &key keyword may only appear once.

Fix syntax error in &key argument.

---

NEWS.md
company.el

(In GUI.)
The look in the terminal is unchanged.

Make scrollbar narrower; move into the right margin

---

company-keywords.el

Add support for [php-ts-mode](https://github.com/emacs-php/php-ts-mode). This package is not yet available in any ELPA, but will be submitted to GNU ELPA in due course.
refs https://github.com/emacs-php/php-ts-mode/issues/55

Add php-ts-mode as an alias of php-mode

---

company-dabbrev.el
company-elisp.el
company.el
test/template-tests.el

`looking-at-p` does not change match data and so should be a bit faster.

treewide: replace `looking-at` with `looking-at-p` if match data unused

---

company-ispell.el

Hi,
Currently, the company-ispell dictionary path doesn't allow to have a `~` in it. For example, with below setting:
```elisp
(setq company-ispell-dictionary "~/.emacs.d/data/misc/english-words.txt")
```
It will error out with message:
```
Company: An error occurred in auto-begin
Company: backend (company-dabbrev company-ispell) error "grep error: look: ~/.emacs.d/data/misc/english-words.txt: No such file or directory" with args (candidates he)
```
So I'm making this PR trying to fix that.

Let company-ispell-dictionary be compatible with the ~user notation.

---

company-dabbrev-code.el
company-files.el
company-ispell.el
company-semantic.el
company.el

This is a minor refactoring.
1.-st commit uses `string-match-p` if match data is unused. The places of replacement were manually examined to make sure it is the case.
2.nd commit should be safe and straightworward replacement of `(string= … "")` with `string-empty-p`
3.rd commit is similar to 2-nd one, except we getting rid of `(equal … "")`. Due to `(equal)` allowing for its arg to be of any type, each changed line was manually examined to make sure that code around it expects a string, so the parameter must be a string as well and not an arbitrary type.

Replace `string-match` with `string-match-p` when appropriate and use `string-empty-p` helper

---

company.el

Currently `company-plainify` expects `line-prefix` to be a string and will fail otherwise. The `line-prefix` text property can be values other than a string, e.g. `(space :width 5)`.
This adds the condition to only attempt to concat the prefix if it is indeed a string.

company-plainify: Only concat string when satisfying stringp

---

NEWS.md
company-capf.el
company.el
test/capf-tests.el

* Internal handling of input interruption with throw-catch that ensures completion is not aborted.
* An interface to opt into `while-no-input` for company-capf which reuses the mechanism.
* As an semi-private feature, the completion table can just `(throw 'interrupted 'new-input)` instead, if it detects new input using its own methods.
~I suppose the main thing left to decide is whether `while-no-input` should be opt-in or opt-out for the capf backend.~
EDIT: just opt-out: see NEWS.

Async no cache flicker

---

company-abbrev.el

previous, tables in `abbrev-minor-mode-table-alist` was not considered

abbrev backend: use abbrev--active-tables to get all tables

---

NEWS.md
company-capf.el

The problem described in https://github.com/joaotavora/eglot/discussions/1127#discussioncomment-7698442 still seems to apply to the Eglot version that comes with Emacs 29.1-29.4, and so might affect a fair number of users, given that an "ELPA core" package doesn't update by default (until the user triggers the first update manually), and a lot of users won't.
I went through the thread, but only managed to reproduce it once (with Emacs 29.1), and not for the lack of trying.
Even if being interruption-safe is the "proper" behavior for completion functions, it seems that at least for this case exposing the problem (i.e. using a capf function inside interrupting context) doesn't really help to have it fixed - and not for the lack of trying.
So it the right move seems to be the change to …

Make the user of while-no-input in company-capf opt-in

---

NEWS.md
company-dabbrev-code.el
company-dabbrev.el

This allows a similar functionality to `dabbrev-friend-buffer-function` for `company-dabbrev(-code)-other-buffers`.

company-dabbrev/-code: allows company-dabbrev(-code)-other-buffers a function

---

NEWS.md
company-capf.el
company-dabbrev-code.el
company-etags.el
company.el
test/async-tests.el
test/capf-tests.el
test/core-tests.el

* New backend action `expand-common`.
* `company-capf` implementation that calls `completion-try-completion` (and support in `company-dabbrev-code` and `company-etags` - when the use of completion styles is enabled in each backend).
* Support for grouped backends returning prefixes/suffixes of different length (resolves #1260).
* Support for `expand-common` in grouped backends as well.
Demo:
[screencast.webm](https://github.com/user-attachments/assets/61d68d98-129b-4249-be20-9aea03a055b6)

company-complete-common: Generalized "expand common" behavior

---

company.el

Hi, Dmitry! I encountered performance issue on completion candidate switching and discovered that problem is in projectile running something heavy in `buffer-list-update-hook`. This PR helps me to fix this issue.

fix performance issue with projectile running hook on candidate switching

---

company-capf.el
company-dabbrev-code.el
company-etags.el
company.el

Minor internal reworking. More edge cases succeed when preview is updated in the middle of fetching completions (the `unhide` handler):
* No jumping after left/right arrow navigation, or deleting a char (don't have to guess which of those happened).
* Consistent behavior between backends which fetch boundaries with completions (capf) and those that parse them out of the input strings (company-files).
* `company--multi-backend-adapter` less dependent on the internal variables of this package (better for `cape`).

Store capf boundaries as markers

---

NEWS.md
company-capf.el
test/capf-tests.el

That cancels completion, forcing the re-fetching of data (after the idle delay) with the new capf.
The result is making sure that completions from one capf aren's displayed where another capf is in force (when that choice is done based on buffer contents). This is probably only relevant with "asynchronous" sources, where the frontends are repainted in the middle of fetching the updated completions.

company-capf--candidates: Abort when the underlying capf changes

---

NEWS.md
company-capf.el
company-files.el
company.el
doc/company.texi
test/core-tests.el

This sets up completion after RET to be restarted after entering a new "field".
Primarily an improvement for file name completion mostly (or other similar completion sources with "boundaries").
Hence the simplification in `company-files`.
This follows what Corfu does in `corfu-complete` but with a tweak which makes it both easier to implement here and closer to `completion--done`: exit-function is called either way after the completion is inserted (but with the symbol `exact` if the new field is entered).

company-finish: Restart completion if entered a new field

---

NEWS.md
company.el
doc/company.texi

This has been a popular configuration for a number of years now. Making it a default for better OOtB experience.
There don't seem to be any significant drawbacks, and the upside is completion workflow that uses fewer keys (arrows or C-n/p are mostly not needed).
Notably, the `backtab` binding seems to work in the terminal as well here, though that probably depend on the terminal emulator and system libs versions.

Use company-complete-common-or-cycle in the default bindings

---

company.el
doc/company.texi

Closes #1502 .
@mandarm, please let us know if the adjusted documentation looks sufficiently clear to you with this PR; and/or if you have any other suggestions.
@dgutov, it is [already documented](https://github.com/company-mode/company-mode/blob/0ae7c293112248a0c36377d6859a95d216ae5e96/company.el#L436) that Company keeps "duplicates" with different annotations. Still, it seems that adding this clarification also to the `company-transformers` docstring may be a good choice.
Also note, that I set the manual's version to 1.0.3-snapshot. [Previously,](https://github.com/company-mode/company-mode/pull/1228#issuecomment-997294550) we considered an approach of publishing only releases. And I am still doubtful whether pre-release documentation should be published.  Still, I guess it could be …

Better document candidates post-processing

---

company-dabbrev-code.el
test/dabbrev-code-tests.el

I've added tests, but here are steps for manual reproducing:
1. emacs -Q
2. Eval:
```elisp
(add-to-list 'load-path "/path/to/company-mode")
(require 'company)
```
3. M-x company-mode
4. Eval:
```elisp
(setq company-backends '(company-dabbrev-code))
(setq company-dabbrev-code-completion-styles '(flex))
```
5. Insert to the buffer
```
scheduled_job
sa_enum
self
se|
```
6. M-x company-complete
7. Displayed candidates:
```
sa_enum
scheduled_job
self
```
8. I expect that `self` would be at the first place.
I noticed that candidates were sorted in the `company--preprocess-candidates` in alphabetical order, because `company-dabbrev-code` always returned nil for `sorted` command.
Now `sorted` returns `t` if `company-dabbrev-code-completion-styles` implies that candidates will be sorted by the …

Fix sorting of dabbrev-code backend for flex style

---

company-keywords.el

This commit will add keywords and names of shell builtins for `sh-mode`. This should fix #820.

Add keywords and builtins for sh-mode

---

company-keywords.el

In Python 3, `async` and `await` were added as keywords starting from version 3.7. Therefore, I have added these keywords to `company-keywords.el`.
---
Thanks to all the maintainers and contributors of company-mode.

Add `async` and `await` as keywords for Python 3
