NEWS.md, company-capf.el
=> Turn :company-prefix-length property into a value

company-keywords.el
These have the same keywords as javascript.
=> company-keywords: Add JSX modes to javascript aliases

company.el
=> Bind message-truncate-lines around call to message in company-echo-show

NEWS.md, company-template.el, test/template-tests.el
Add binding to `company-template-nav-map` to delete template and move to next.
Resolves #657
=> Add function and binding to delete template fields and move to next

company-tng.el, company.el
See commit messages and the discussions at #731
=> company-tng: Suppress post-completion

company.el
When writing your first company backend, it's really helpful to be able to run
the example backend with M-x. Many real company backends are interactive too.
=> Make example backend interactive

company-keywords.el
I've also aliases rjsx-mode to javascript-mode
=> Update Javascript and Python keywords

company-keywords.el
=> add some golang fake keywords for a better programming experience

NEWS.md, company.el
Sample usage:
`(setq company-idle-delay (lambda () (if (company-in-string-or-comment) nil 0.3)))`
=> Make company-idle-delay support predicate function

test/capf-tests.el
* test/capf-tests.el (cl-lib): Require it.
(company--remove-but-these-properties): New helper.
(company-basic-capf-highlighting)
(company-non-prefix-fancy-capf-highlighting)
(company-non-prefix-modest-capf-highlighting): Use it.
=> Make tests resilient to arbitrary text properties in completions

company-tng.el
Following a discussion at #881
=> company-tng: Document post-completion and yasnippet issues

company-clang.el
Update regex template string to match new clang (InBase) declaration tags.
=> update regex template to match (InBase) declarations

company-etags.el
See #903 
I rewrite the algorithm from the scratch, now the code is much more efficient.
Test with latest linux kernel code.
- The initial loading takes 9 seconds to read tags file and prepare all the candidate. The old algorithm takes more than 120 seconds.
- After initial loading, if CLI program `diff` exists, the new tag name is extracted from diff output. It's less than 0.5 second. The old code need 10~20 seconds at best, or 120 seconds at worst
- `(all-completion prefix all-tags)` is as 50 times fast as old version.
=> speed up company-etags

company-etags.el
Reverts company-mode/company-mode#904
=> Revert "speed up company-etags"

NEWS.md, company.el, test/frontends-tests.el
https://github.com/company-mode/company-mode/issues/889
=> add option to show number on the left

company-bbdb.el
=> company-bbdb: Support more headers like From:

company-yasnippet.el
=> Add the docbuffer in company-yasnippet

README.md
=> Fix badge url

company.el
Adds `company--face-attribute FACE ATTR`, which resolves any remappings of FACE (with face-remap) recursively. This solution is slightly different to what was suggested in #1019, but handles more edge cases.
This fixes #1019, #1013, https://github.com/hlissner/emacs-solaire-mode/issues/37 and https://github.com/hlissner/doom-emacs/issues/4013
----
The function is 15L, but altogether 17L are modified. Whether or not I need to do the FSF CA for this, it's probably a good idea I do (won't be the last time I contribute to GPL'd code). How would I go about doing that?
=> Fix tooltip background stretching to EOL

company.el
See [#756](https://github.com/company-mode/company-mode/issues/756#issuecomment-810306170).
I wasn't sure which icons should be the default... so I just picked some random greek unicode glyphs. You can probably pick more appropriate ones.
=> (margin): Add tty compatible margin function

company.el
=> company-text-icons-mapping: Merge faces/colors into its format

.github/ISSUE_TEMPLATE/bug-report.md
=> Add Bug Report issue template

company-abbrev.el
=> Make company-abbrev expand abbreviations after completion

Makefile
Hi Dmitry, I kept all the commits for now so to briefly explain each change.
Let me know if it'd be sufficient or you'd prefer to have the commits squashed.
=> Makefile updates and fixes

doc/company.texi
Minor fix in manual: company-search-flex-regexp was missing
=> User manual: Minor fixes

company-capf.el
=> company-capf: only rm tags-capf from capf if we use company-etags

company-keywords.el
Hello guys, i updated company-keywords.el, please merge it. @dgutov
=> Add nim programming language keywords to company-keywords.el

company-clang.el
hello @dgutov, this pull request fixs the #1332 issue, please merge it.
=> fix company-clang-version function

company-clang.el
Reverts company-mode/company-mode#1333
=> Revert "fix company-clang-version function"

company.el, doc/company.texi
Let a doc-bore to suggest the adjustments.
There was also a notion to replace the argument name `toggle-auto-update` by `arg` or `toggle` but it was dropped.
=> Adjust recently added docs

doc/company.texi
=> User manual: fix F1 key typo

company-keywords.el
Part of the keywords is context sensitive.
Thank you.
=> Add Crystal-mode into company-keywords

company-keywords.el
Hi there! I haven't signed the FSF copyright assignment papers—could someone please help me get that started?
=> Add keywords for Elixir

NEWS.md, company.el, test/frontends-tests.el
This feature started out in the issue #1388.
The method is fairly different from the previous one, so this could use more testing.
=> Improve popup rendering with wide characters in buffer or popup

company-keywords.el
Adds the list of Ocaml keywords for caml-mode and tuareg-mode.
=> Update company-keywords.el with OCaml keywords

company.el
This is a further elaboration of the fix to #778
=> Abort completion also on a few other entry points to completion-at-point
